name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install --global corepack@latest
      - run: corepack enable
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm biome ci .
      - name: Install playwright
        run: pnpx playwright install chromium
      - name: Test
        run: pnpm test
        env:
          CI: true
      - name: Build
        run: pnpm build

